In [1]:
import pandas as pd
import dxpy

# Classweight

In [2]:
dxpy.download_dxfile('file-GpY7gBQJjKX0KX3k20Y6FpXq', 'cw_features.csv')

In [3]:
cw_df = pd.read_csv('cw_features.csv', sep='\t')

In [4]:
cw_df.head(15)

     feature  importance
0        grs    0.024352
1   UKBB_GRS    0.015627
2       paep    0.010124
3       fshb    0.007456
4        cga    0.006966
5     chrdl2    0.004494
6       rln2    0.002339
7      gdf15    0.002274
8       ccl3    0.001995
9       alpp    0.001829
10     lmnb2    0.001691
11      msmb    0.001606
12     fgfr2    0.001585
13    flt3lg    0.001552
14     lamp3    0.001505

# Under Sampling

## Random Under Sampling

In [5]:
dxpy.download_dxfile('file-GpV8Yp8JjKXGpKXp867Gq73Y', 'RUS_features.csv')

In [6]:
rus_df = pd.read_csv('RUS_features.csv', sep=',')

In [7]:
rus_df.head(15)

     feature  importance
0        grs    0.019879
1   UKBB_GRS    0.019617
2       paep    0.009285
3        cga    0.008142
4       fshb    0.006029
5       rln2    0.004877
6     chrdl2    0.004597
7       klk4    0.002401
8        prl    0.002238
9       sdk2    0.002187
10     gdf15    0.001975
11    tspan1    0.001891
12     fabp1    0.001760
13     lamp3    0.001583
14      cst6    0.001576

## Nearmiss

In [8]:
dxpy.download_dxfile('file-GpVvB80JjKXJ5GVJb7B1FqQG', 'nearmiss_features.csv')

In [9]:
nearmiss_df = pd.read_csv('nearmiss_features.csv', sep=',')

In [10]:
nearmiss_df.head(15)

     feature  importance
0        grs    0.015626
1   UKBB_GRS    0.006095
2      tsnax    0.004020
3       yod1    0.003622
4      morc3    0.003097
5     mthfd2    0.003023
6    scgb2a2    0.003008
7    slc12a2    0.002984
8     dnajb2    0.002731
9     snrpb2    0.002726
10    ranbp1    0.002561
11    adgre1    0.002308
12    prkag3    0.002303
13      mdh1    0.002237
14   sh3glb2    0.002105

## Clustercentroids

In [11]:
dxpy.download_dxfile('file-GpVy8Y8JjKX6v5vVXQB8jB4k', 'clustercentroids_features.csv')

In [12]:
clustercentroids_df = pd.read_csv('clustercentroids_features.csv', sep='\t')

In [13]:
clustercentroids_df.head(15)

     feature  importance
0        grs    0.014660
1   UKBB_GRS    0.012393
2       paep    0.007847
3     mapre3    0.003545
4     lypla2    0.003524
5       nenf    0.003195
6    cntnap4    0.003162
7    kir2ds4    0.002905
8       rln1    0.002897
9     vcpkmt    0.002801
10    iglon5    0.002728
11      get3    0.002707
12      ugdh    0.002561
13     myl6b    0.002507
14     kdm3a    0.002507

# Over Sampling

## Random Over Sampling

In [14]:
dxpy.download_dxfile('file-GpXJXB8JjKX48k0fF8B2Q58Y', 'ROS_features.csv')

In [15]:
ros_df = pd.read_csv('ROS_features.csv', sep='\t')

In [16]:
ros_df.head(15)

     feature  importance
0        grs    0.019405
1   UKBB_GRS    0.013167
2       paep    0.006441
3        cga    0.005320
4       fshb    0.003072
5     chrdl2    0.002485
6      lamp3    0.001974
7       rln2    0.001873
8     cxcl17    0.001842
9      gdf15    0.001597
10       prl    0.001443
11      klk4    0.001341
12      bst2    0.001327
13       dpt    0.001247
14       cpm    0.001227

## ADASyn

In [17]:
dxpy.download_dxfile('file-GpY67jjJjKXB16vfqYgJPfQq', 'ADASyn_features.csv')

In [18]:
adasyn_df = pd.read_csv('ADASyn_features.csv', sep='\t')

In [19]:
adasyn_df.head(15)

     feature  importance
0   UKBB_GRS    0.025725
1        grs    0.020645
2       paep    0.009958
3       psca    0.006018
4        cga    0.005452
5      klk12    0.004952
6       fshb    0.004736
7     chrdl2    0.004445
8     lgals4    0.003291
9        zp3    0.003161
10       cfh    0.003113
11   txndc15    0.002914
12      sdk2    0.002683
13     cntn2    0.002455
14      rln2    0.002446

## SMOTE

In [20]:
dxpy.download_dxfile('file-GpXX2zjJjKX5787z0pj0gq7B', 'SMOTE_features.csv')

In [21]:
smote_df = pd.read_csv('SMOTE_features.csv', sep='\t')

In [22]:
smote_df.head(15)

     feature  importance
0   UKBB_GRS    0.023356
1        grs    0.023311
2       paep    0.009744
3      klk12    0.007437
4        cga    0.005645
5       fshb    0.005506
6       psca    0.005416
7     chrdl2    0.003656
8     col9a1    0.003429
9       sdk2    0.003371
10       cfh    0.003030
11   ceacam1    0.002941
12    lgals4    0.002751
13   txndc15    0.002564
14     cntn2    0.002422